# Intro to Tensors with Numpy
* https://machinelearningmastery.com/introduction-to-tensors-for-machine-learning/#:~:text=A%20tensor%20is%20a%20generalization,understood%20as%20a%20multidimensional%20array.&text=It%20is%20a%20term%20and,described%20in%20terms%20of%20tensors.


* What is a tensor?
> "A type of data structure from linear algebra. They are similar to vectors and matrices in that you can perform arithmetic operations with them"

* Notebook Goals:
1. Understand how tensors are a generalization of matrices and are represented using n-dimensial arrays
2. Understand how to perform element-wise operations with tensors
3. Understand how to perform the tensor product


### What are Tensors?
> Tensors are multidimensional arrays
> Generally speaking, any array of numbers arranged on a regular grid w/ a variable number of axes is a tensor

Consider a vector $\vec{v}$ that is <b>one-dimensional</b>. The tensor equivalent is a <b>first order tensor</b>. 

Now consider a matrix which is a <b>two-dimensional</b> -- ie a <b>second order tensor</b>.

Consider the following a 3x3x3 tensor represented as a NumPy ndarray

In [2]:
import numpy as np
T = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
print(T.shape) 
print(T)

(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [11]:
# length of the ndarray denotes the number dimensions
print("{}-dimensional array".format(len(T.shape)))

3-dimensional array


In [13]:
print("Axis 0: Level 0\n",T[0],"\n") # accessing axis 0 --> accessing the level 0
print("Axis 0: Level 1\n",T[1],"\n") # accessing axis 0 still --> accessing level 1
print("Axis 0: Level 2\n",T[2],"\n") # further accessing axis 0 --> accessing level 2

Axis 0: Level 0
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Axis 0: Level 1
 [[11 12 13]
 [14 15 16]
 [17 18 19]] 

Axis 0: Level 2
 [[21 22 23]
 [24 25 26]
 [27 28 29]] 



In [12]:
print(T[0][0]) # accessing a specific row=0 for a particular level=0, level 0 row 0
print(T[0][0][0]) # accessing a specified row=0, col=0, and level=0

[1 2 3]
1


### Element-Wise Tensor Operations
### Tensor Addition

Element-wise addition of two tensors of same dimensions results in a new tensor w/ the same dimensions such that each scalar val is the element-wise addition of the scalars in the parent tensors. This applies the same concepts when working with matrix addition.
<br>
>$\begin{pmatrix}
a_1 & a_2 & a_3\\
a_4 & a_5 & a_6
\end{pmatrix} 
+ 
\begin{pmatrix}
b_1 & b_2 & b_3\\
b_4 & b_5 & b_6
\end{pmatrix}
=
\begin{pmatrix}
a_1 + b_1 & a_2+ b_2 & a_3+b_3\\
a_4+b_4 & a_5+b_5 & a_6+b_6
\end{pmatrix}$

In [14]:
# tensor addition
A = array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
B = array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
C = A + B
print(C)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


### Tensor Subtraction
The same principles that apply for addition hold for subtraction here. 

Thoughts:
* Can you add tensors of differing dimensions? Matrix addition/subtraction of differing in dimensions is illegal $\therefore$ this should also apply to tensors as well

### Tensors Multiplication: Hadamard Product
Multiplication of tensors of the same dimensions results in a new tensor of the same starting dimensions. It is essentially the cross product of 2 matrices.

>$\begin{pmatrix}
a_1 & a_2 & a_3\\
a_4 & a_5 & a_6
\end{pmatrix} 
\times
\begin{pmatrix}
b_1 & b_2 & b_3\\
b_4 & b_5 & b_6
\end{pmatrix}
=
\begin{pmatrix}
a_1 + b_1 & a_2+ b_2 & a_3+b_3\\
a_4+b_4 & a_5+b_5 & a_6+b_6
\end{pmatrix}$


In [15]:
# tensor Hadamard product
from numpy import array
A = array([
  [[1,2,3],    
   [4,5,6],    
   [7,8,9]],
    
  [[11,12,13],
   [14,15,16],
   [17,18,19]],
    
  [[21,22,23],
   [24,25,26], 
   [27,28,29]],
  ])
B = array([
  [[1,2,3],    
   [4,5,6],    
   [7,8,9]],
    
  [[11,12,13], 
   [14,15,16],
   [17,18,19]],
    
  [[21,22,23], 
   [24,25,26], 
   [27,28,29]],
  ])
C = A * B
print(C)

[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[121 144 169]
  [196 225 256]
  [289 324 361]]

 [[441 484 529]
  [576 625 676]
  [729 784 841]]]


### Tensor Division
Same principles from mulitplication, subtraction, and addition apply here.

### More Tensor Multiplication

Usage of the tensor product denoted by $\otimes$<br>
$a=(a_1,a_2), b=(b_1,b_2)$<br>
$c = a \otimes b$<br>

$\equiv\begin{pmatrix}
a_1 \times [b_1, b_2 ]\\
a_2 \times [b_1, b_2]
\end{pmatrix}$  
<br>
Unrolled:
<br>
<br>
$\equiv\begin{pmatrix}
a_1 \times b_1 & a_1\times b_2\\
a_2 \times b_1 & a_1 \times b_2
\end{pmatrix}$
<br>
<br>
$\equiv\begin{pmatrix}
a_1b_1 & a_1b_2\\
a_2b_1 & a_1b_2
\end{pmatrix}$

In [20]:
# tensor product
# from numpy import tensordot
A = np.array([1,2])  # 2x1 matrix
B = np.array([3,4]) # 1x2 matrix 
C = np.tensordot(A, B, axes=0) # multiplication on a particular axis 
print(C)
A * B

[[3 4]
 [6 8]]


array([3, 8])

In [22]:
print(A.shape)
print(B.shape)

(2,)
(2,)


Can be slightly confusing to understand what's going on here from the blog post. 
<br>
Referring to the numpy documentation:
https://numpy.org/doc/stable/reference/generated/numpy.tensordot.html
<br>
We see that axes specifies the type of operation the function tensorproduct performs. If axes=0, then specified execution of tensor product $a\otimes b$. If axes=1, then specified tensor dot product $a\cdot b$. If axes=2, then perform a double contraction, $a : b$.
<br>


In [24]:
np.tensordot(A,B,axes=1) # dot product calculated 

array(11)

* Despite understanding the basis of a tensor, the major lingering question is how do tensors relate to neural networks?
* Tensor Visuals: https://www.datacamp.com/community/tutorials/investigating-tensors-pytorch
* More about the representations of data in the form tensors: 
https://medium.com/mlait/tensors-representation-of-data-in-neural-networks-bbe8a711b93b